<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>Admin Home Page</title>
	<link rel="stylesheet" href="/css/base.css" />
	<link rel="stylesheet" href="/css/home.css" />
</head>
<body>
	<div class="page-title container">Home Page</div>
	<div class="container">
		<div class="flex-box">
			<span>ID</span><span><?= $admin_id ?></span>
		</div>
		<div class="flex-box">
			<span>Account</span><span><?= $admin_account?></span>
		</div>
		<div class="flex-box">
			<span>Name</span><span><?= $admin_name ?></span>
		</div>
		<div class="flex-box">
			<span>Grade</span><span><?= $admin_grade ?></span>
		</div>
		<div class="flex-box">
			<span>Rate</span><span><?= $admin_rate ?></span>
		</div>
		<div class="flex-box">
			<span>Authority</span><span><?= $admin_authority ?></span>
		</div>
	</div>
	<script src="/js/comm/jquery-1.8.2.min.js"></script>
</body>
</html>