<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>登录-管理员</title>
	<link rel="stylesheet" href="/css/base.css" />
	<link rel="stylesheet" href="/css/login.css" />
</head>
<body class="body-flex">
	<div id="login">		
		<img src="/img/me.png"/>
		<div class="login-title">Scholarship Login</div>
		<form id="form">
			<label for="userid">Account</label>
            <input id="userid" type="text" name="admin_id" placeholder="input your account"/>
            <label for="password">Password</label>
           	<input id="password" type="password" name="admin_pass" placeholder="input your password"/>
      		<button id="login-button" type="button" >Login</button>
        </form>
	</div>
	<script src="/js/comm/jquery-1.8.2.min.js"></script>
	<script src="/js/admin/login.js"></script>
</body>
</html>