<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<title>Admin Setting</title>
	<link rel="stylesheet" href="/css/base.css" />
	<link rel="stylesheet" href="/css/setting.css" />
</head>
<body>
	<!-- <div class="flex-box container">
		<span>Admin Setting</span>
    	<span>Scholarship Base Setting</span>
    	<span>Self Setting</span>
	</div>  -->
	<div class="page-title container">Admin Setting Page</div>
	<div class="container">
    	<div class="flex-box">
    		<span class="shade">Admin Setting</span>
        	<span class="shallow">Scholarship Base Setting</span>
        	<span class="middle">Self Setting</span>
        </div>
        <div class="flex-box">
    		<span class="shallow">Admin Setting</span>
        	<span class="middle">Scholarship Base Setting</span>
        	<span class="deep">Self Setting</span>
        </div>
        <div class="flex-box">
    		<span class="default">Admin Setting</span>
        	<span class="deep">Scholarship Base Setting</span>
        	<span class="shade">Self Setting</span>
        </div>
	</div>
	
	<!-- <div class="flex-box container">
		<span>Admin Setting</span>
    	<span>Scholarship Base Setting</span>
    	<span>Self Setting</span>
	</div> -->
	<div class="container">
		<form>
			<label>Department</label>
			<select>
				<option>Management and Economic</option>
				<option>Mechine Engineer</option>
				<option>Computer Science and Technology</option>
				<option>Others</option>
			</select>
			<label>Grade</label>
			<select>
			<?php 
				$year = date('Y');
				for($i = 0; $i < 3; $i ++):
			?>
				<option><?= $year -- ?></option>
			<?php endfor;?>
			</select>
			<label>Year</label>
			<select>
				<option>2016</option>
			</select>
			<button type="button">Confirm</button>
		</form>
	</div>
	<div class="container">
    	<div class="flex-box">
    		<span>1</span>
        	<span>2</span>
        	<span>3</span>
        </div>
        <div class="flex-box">
    		<span>4</span>
        	<span>5</span>
        	<span>6</span>
        </div>
        <div class="flex-box">
    		<span>7</span>
        	<span>8</span>
        	<span>9</span>
        </div>
	</div>

</body>
</html>